networks:
  weather-app:
    driver: bridge

services:
  weather-db:
    container_name: weather-db
    image: postgres:15
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=weather_api_development
      - POSTGRES_USER=weather_api
      - POSTGRES_PASSWORD=password
    networks:
      - weather-app
  
  weather-cache:
    container_name: weather-cache
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - weather-app

  weather-api:
    container_name: weather-api
    build: ./weather-api
    volumes:
      - ./weather-api:/app
    environment:
      - REDIS_URL=redis://weather-cache:6379/0
      - API_KEY=079247d7d47f424b96c143604252907
      - BASE_URL=https://api.weatherapi.com/v1
    ports:
      - "3000:3000"
    working_dir: /app
    entrypoint:
      - ./entrypoint.sh
    depends_on:
      weather-db:
        condition: service_started
      weather-cache:
        condition: service_started
    networks:
      - weather-app